# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

exec-once = nwg-drawer -r -c 6 -is 64 -spacing 8 -mt 100 -mb 100 -ml 250 -mr 250