# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Global transparency for all windows (inactive only)
windowrule = opacity 1.0 0.80, match:class .*

# Disable blur for all xwayland apps
windowrule = no_blur on, match:xwayland 1

#Exceptions
windowrule = match:class .*codium.*, opacity 0.90 override 0.90 override
windowrule = match:class .*io.missioncenter.MissionCenter.*, opacity 0.80 override 0.80 override
windowrule = match:class .*org.gnome.Nautilus.*, opacity 0.90 override 0.90 override
windowrule = match:class .*org.kde.dolphin.*, opacity 0.90 override 0.90 override

#Tiktok
windowrule = match:class .*chrome-www.tiktok.com__en_-Default.*, opacity 0.99 override 0.99 override
windowrule = float on, size 753 1032, move 4 44, match:class ^chrome-www.tiktok.com__en_-Default$

#Spotify
windowrule = float on, size 800 600, move 150 206, match:class ^spotify$
windowrule = match:class .*spotify.*, opacity 0.90 override 0.90 override no_blur off

#Instagram
windowrule = match:class .*chrome-www.instagram.com__-Default.*, opacity 0.99 override 0.99 override
windowrule = float on, size 780 1032, move 1136 44, match:class ^chrome-www.instagram.com__-Default$

#Kitty
windowrule = match:class .*kitty.*, opacity 0.85 override 0.85 override no_blur off
windowrule = float on, size 1085 740, move 440 200, match:class ^kitty$
