general {
    col.active_border = rgba(8b948077)
    col.inactive_border = rgba(41493955)
}

misc {
    background_color = rgba(10150cFF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Google Sans Flex Medium, Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(10150cFF)
        col.text = rgba(e0e4d6FF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(e0e4d6), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(e0e4d6), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(e0e4d6), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrule = border_color rgba(ffb1c7AA) rgba(ffb1c777), match:pin 1
